service: task-management-system

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  timeout: 30
  environment:
    TASKS_TABLE: ${self:service}-tasks
    JWT_SECRET: my_jwt_secret
    BUCKET_NAME: tms-uploads-bucket

plugins:
  - serverless-offline
  - serverless-localstack

custom:
  localstack:
    stages:
      - local

functions:
  createTask:
    handler: handler.createTask
    events:
      - http:
          path: /tasks
          method: post
          cors: true

  getAllTasks:
    handler: handler.getAllTasks
    events:
      - http:
          path: /tasks
          method: get
          cors: true

  getTaskById:
    handler: handler.getTaskById
    events:
      - http:
          path: /tasks/{id}
          method: get
          cors: true

  updateTask:
    handler: handler.updateTask
    events:
      - http:
          path: /tasks/{id}
          method: put
          cors: true

  deleteTask:
    handler: handler.deleteTask
    events:
      - http:
          path: /tasks/{id}
          method: delete
          cors: true

  handleSQSMessage:
    handler: handler.handleSQSMessage
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - TaskQueue
              - Arn

  hourlyTask:
    handler: handler.hourlyTask
    events:
      - schedule:
          rate: rate(1 hour)

  handleS3Upload:
    handler: handler.handleS3Upload
    events:
      - s3:
          bucket: ${self:provider.environment.BUCKET_NAME}
          event: s3:ObjectCreated:*

resources:
  Resources:
    TasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TASKS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    TaskQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: task-queue

    UploadsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
        VersioningConfiguration:
          Status: Enabled
        AccessControl: Private
