org: ac21ita
app: task-management-system
service: task-management-system

custom:
  tableName: "tasks-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [TasksTable, Arn]
  environment:
    TASKS_TABLE: ${self:custom.tableName}

functions:
  createTask:
    handler: handler.createTask
    events:
      - http:
          path: tasks
          method: post

  getAllTasks:
    handler: handler.getAllTasks
    events:
      - http:
          path: tasks
          method: get

  getTaskById:
    handler: handler.getTaskById
    events:
      - http:
          path: tasks/{id}
          method: get

  updateTask:
    handler: handler.updateTask
    events:
      - http:
          path: tasks/{id}
          method: put

  deleteTask:
    handler: handler.deleteTask
    events:
      - http:
          path: tasks/{id}
          method: delete

resources:
  Resources:
    TasksTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: taskId
            AttributeType: S
        KeySchema:
          - AttributeName: taskId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
